// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apjrbcqaapviguncwrlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwanJiY3FhYXB2aWd1bmN3cmxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTUzOTcsImV4cCI6MjA3MDY3MTM5N30.pSfkJguK8pHxHb7ehlHXpIKCoiSQ3bQOldiN-0W_70I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});